export const Icons = {
  Delete: 'trash-can-outline',
  Edit: 'playlist-edit',
  ArrowRight: 'chevron-right',
  DeleteOutline: 'delete-outline',
  Search: 'magnify',
  Close: 'close',
  Weight: 'weight',
  Repeat: 'repeat-variant',
  Plus: 'plus',
  Dumbell: 'dumbbell',
  List: 'format-list-bulleted',
  CheckboxCircle: 'checkbox-marked-circle',
  PlusCircleOutline: 'plus-circle-outline',
  Checkbox: 'check',
  Earth: 'earth',
  Logout: 'logout',
  Home: 'home',
  Settings: 'tune',
  Login: 'login',
  Register: 'account-plus',
  DarkMode: 'theme-light-dark',
} as const;
